services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aequitas_prototype
    ports:
      - "5174:5173"
    volumes:
      # Mapeia o código fonte para o container para permitir Hot-Reload
      - .:/app
      # Evita que o node_modules do host sobrescreva o do container
      - /app/node_modules
